# Generated by Django 2.2.1 on 2019-07-01 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_articles_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='user',
        ),
        migrations.AddField(
            model_name='articles',
            name='useremail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='useremail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articles',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
