# Generated by Django 2.2.1 on 2019-07-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190701_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='useremail',
            new_name='user',
        ),
    ]
