# Generated by Django 2.2.1 on 2019-07-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190701_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
